sudo: required
service:
        - docker
          
before_install:
        - docker build -t  mohsenm12669/dokcer-react -f Dockerfile.dev . 
script:
        - docker run mohsenm12669/dokcer-react npm run test -- --coverage
